-- 20250819_create_static_pages.sql
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS StaticPages (
  slug VARCHAR(50) PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SET FOREIGN_KEY_CHECKS=1;
